stages:
- test
- build_backend
- build_image

variables:
  IMAGE_NAME_DEV: backend_dev:$CI_COMMIT_REF_SLUG

test_backend:
  stage: test
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end test
  artifacts:
    paths:
    - target/
    expire_in: 1 week

build_backend:
  stage: build_backend
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end compiler:compile war:war
  artifacts:
    paths:
    - target/
    expire_in: 1 week

build_image_dev:
  stage: build_image
  only:
    - master
    - ft/gitlab_ci
  script:
    - docker build --pull -t $IMAGE_NAME_DEV -f Dockerfile.dev .
