stages:
- test
- build
- build_image

variables:
  IMAGE_NAME_DEV: $CI_REGISTRY/jukebox/backend/dev:$CI_COMMIT_REF_SLUG
  IMAGE_NAME_PRO: $CI_REGISTRY/jukebox/backend/pro:$CI_COMMIT_REF_SLUG

unit_test:
  stage: test
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end test
    - cat target/site/jacoco/index.html
  artifacts:
    paths:
    - target/
    - target/site/jacoco/
    expire_in: 1 week

backend:
  stage: build
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end compiler:compile war:war
  artifacts:
    paths:
    - target/
    expire_in: 1 week

docker_images:
  stage: build_image
  only:
    - master
    - ft/gitlab_ci
    - ft/gitlab_ci_test
  script:
    - docker build --pull -t $IMAGE_NAME_PRO .
    - docker build --pull -t $IMAGE_NAME_DEV -f Dockerfile.dev .
