stages:
- test
- build_backend
- build_image

variables:
  IMAGE_DEV_TAG: 129.217.62.109:4790/jukebox/jukebox/backend_dev:$CI_COMMIT_REF_SLUG

test_backend:
  stage: test
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end test
  artifacts:
    paths:
    - target/
    expire_in: 1 week

build_backend:
  stage: build_backend
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end compiler:compile war:war
  artifacts:
    paths:
    - target/
    expire_in: 1 week

build_image_dev:
  stage: build_image
  only:
    - master
    - ft/gitlab_ci
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN 129.217.62.109:4790
    - docker build --pull -t $IMAGE_DEV_TAG -f Dockerfile.dev .
    - docker push $IMAGE_DEV_TAG
