stages:
- test
- build

unit_test:
  stage: test
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end test
    - cat target/site/jacoco/index.html
    - cp -r target/site/jacoco .
  artifacts:
    name: code_coverage_$CI_COMMIT_REF_SLUG
    paths:
    - jacoco/

backend:
  stage: build
  dependencies: []
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end compiler:compile war:war
  artifacts:
    paths:
    - target/*.war
    expire_in: 1 week
