stages:
- test
- build
- build_image

variables:
  IMAGE_NAME_DEV: backend_dev:$CI_COMMIT_REF_SLUG
  IMAGE_NAME_PRO: backend_pro:$CI_COMMIT_REF_SLUG

unit_test:
  stage: test
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end test
  artifacts:
    paths:
    - target/
    expire_in: 1 week

backend:
  stage: build
  image: dockette/mvn
  script:
    - mvn --batch-mode --quiet --fail-at-end compiler:compile war:war
  artifacts:
    paths:
    - target/
    expire_in: 1 week

development:
  stage: build_image
  only:
    - master
    - ft/gitlab_ci
  script:
    - docker build --pull -t $IMAGE_NAME_DEV -f Dockerfile.dev .

production:
  stage: build_image
  only:
    - master
    - ft/gitlab_ci
  script:
    - docker build --pull -t $IMAGE_NAME_PRO .
