FROM tomcat:9-alpine
MAINTAINER Danny Textores <textores.danny@gmail.com>

# remove default webapp, listen on port 80, enable hot reload
RUN rm -rf /usr/local/tomcat/webapps/ROOT && \
    sed -i /usr/local/tomcat/conf/server.xml -e 's/port="8080"/port="80"/g' && \
    sed -i /usr/local/tomcat/conf/context.xml -e 's/<Context>/<Context reloadable="true">/'

# environment variables for remote debugging
ENV JPDA_ADDRESS=8000
ENV JPDA_TRANSPORT=dt_socket

# wait for debugger to attach
ENV JPDA_SUSPEND=y

# set environment variables TODO remove, add to compose file
ENV SPOTIFY_CLIENT_ID=06b4a989398d48728a998eb0450d2e5a
ENV SPOTIFY_CLIENT_SECRET=22b61a1301634a72aae6e6b8064c3ecd
ENV JUKEBOX_INVITE_KEY=xxx

# mount webapp as volume
VOLUME /usr/local/tomcat/webapps/ROOT.war

# expose remote debugging port
EXPOSE 8000

# log4j configfile
COPY log4j2.xml /usr/local/tomcat/log4j2.xml
ENV LOG4J_CONFIGURATION_FILE=/usr/local/tomcat/log4j2.xml

# startup script to run tomcat with debugging enabled
COPY startdebug.sh /
CMD ["/startdebug.sh"]
