package de.reactivejukebox.logger;

public enum EntryCol {
    // Order sensitive!
    TIMESTAMP,
    USER,
    EVENT,
    RADIO,
    HISTORY,
    SONG,
    USER_ACTION,
    SONG_FORWARD,
    SONG_RUNTIME,
    ALBUM,
    RATING_SONG,
    ARTIST,
    GENRE,
    RATING_SPEED,
    RATING_DYNAMIC,
    RATING_MOOD,
    ALGORITHM,
    YEAR_START,
    YEAR_END,
    DYNAMIC,
    AROUSAL,
    VALENCE,
    SPEED_MIN,
    SPEED_MAX,
    JSON,
}
